# Creating a 2D numpy array 

In [28]:
import numpy as np # import python's numpy library. numpy contains plenty of mathematical tools
import random # import random function in python

no_of_rows = 100 # arbitrary rows for 2D array

main_list = list()
for i in range(no_of_rows):
    dummy_list = list()
    no_of_columns = 100
    for i in range(no_of_columns):
        dummy_list.append(random.randint(1,10e5))
    main_list.append(dummy_list)

array_2D = np.array(main_list) # creating a 2D array 

# selecting row 1 from array_2D
ROW_1 = array_2D[1]
# print(ROW_1)

# selecting column 1 from array_2D
COLUMN_1 = array_2D[:,1]
# print(COLUMN_1)

# selecting a sub-region and altering that region
SUB_REGION_1 = array_2D[10:21,50:71] # selecting row 10 to 20 and column 50 to 70
SUB_REGION_1 += random.randint(1,100)
# print(array_2D)

# operations on all rows
new_array_2D_add = array_2D + random.randint(1,1000)
new_array_2D_multiply = array_2D * random.randint(1,1000)
new_array_2D_substract = array_2D - random.randint(1,1000)
new_array_2D_divide = array_2D / random.randint(1,1000)

# location of specific region based on conditional assigment on array
new_array_2D_extract = np.where(array_2D > 1000, array_2D, 100000) 
                                        # when True, yield array_2D, else yield 100000
print(new_array_2D_extract)
print('')
print(len(array_2D))
print('')
print(len(new_array_2D_extract))

[[550480 567311 460985 ... 448639 911949 901157]
 [138689 958776 139310 ... 961782 191351 527783]
 [323435 414610 102563 ... 715130 954401  98669]
 ...
 [331264 775411 117789 ... 727935 838605 400264]
 [509377 392106 479019 ... 952778 152480 188164]
 [141910 377472 901713 ... 887933 499074 886897]]

100

100
